### ISSUE TITLE
[OSX 10.10] cannot find fink command after running Install Fink.tool

### ISSUE THREAD

**Issue by jdmswong** [fink/scripts#36]
My machine cannot find fink after downloading the raw ```Install Fink.tool```.  I don't know if restarting will fix is, but I cannot restart easily now.  How can I enable the ```fink``` command?

**Comment by dak180** [comment]
`Install Fink.tool` is a executable script, if you do not run it, nothing will happen.

Once it is run, you will need to reopen any terminal windows besides the one you run `Install Fink.tool` from for `fink` or anything installed by it to be picked up.

**Comment by jdmswong** [comment]
I ran ```Install Fink.tool``` however, opening a new terminal window does not fix the issue.

**Comment by akhansen** [comment]
Did you run /sw/bin/pathsetup.sh ?  The fink bootstrap should have instructed you to do that.

**Comment by jdmswong** [comment]
running that command and opening a new window worked!  I looked over the last few lines of the fink install script, but guess I missed that nugget

**Comment by dak180** [comment]
@akhansen `Install Fink.tool` should do that just before it runs selfupdate for the first time.

**Comment by dak180** [comment]
@jdmswong the `Install Fink.tool` script is meant to automate the process of setting up fink for the first time; running the commands in the script manually mostly defeats the purpose of it.

**Comment by jdmswong** [comment]
I don't think it did, since I posted this issue after ```Install
Fink.tool``` completed execution.  I would post the logs but no longer have
them
