### ISSUE TITLE
Syntax error Expected end of line, etc. but found identifier.

### ISSUE THREAD

**Issue by Ulivalo** [fink/scripts#40]
Hello. 
I am really new with this and I am trying to install fink. I have macOS 10.12 and I am copying the code provided here:
https://github.com/fink/scripts/blob/master/srcinstaller/Install%20Fink.tool

into the script editor and when I try to run the script I receive a message:
"Syntax error Expected end of line, etc. but found identifier."
and the script editor selects fetchBin on the line "function fetchBin {"

what can I do in order to solve this? I hope you can help me with this

**Comment by dak180** [comment]
Download [InstallFink.tgz](https://github.com/fink/scripts/releases/latest) and run the resulting `Install Fink.tool` file on your computer.
