### ISSUE TITLE
Error while executing

### ISSUE THREAD

**Issue by dagsagrinbergs** [fink/scripts#41]
Hi!

Maybe I don't know how to execute the script properly, but just executing with `zsh Fink.tool` returns `Fink.tool:115: bad floating point constant`

`uname -a | cut -d' ' -f3` returns "16.7.0"

I can't seem to find any other way to install Fink on 10.12, so it would be great if you could assist me with executing the script :).

**Comment by dagsagrinbergs** [comment]
Double clicking "Install Fink.tool" just does nothing...

**Comment by dmacks** [comment]
The relevant two lines seem to be:

>DarwinVersion="$(uname -a | cut -d' ' -f3)"
>...
>if [[ "${DarwinVersion}" < "13" ]]; then ...

I have no idea how that is failing. The user's debugging suggests $DarwinVersion is being set correctly, but even if it's wildly mis-defined, a string comparison with quoted values doesn't seem like a syntax error.

String comparison with a kernel-number looks risky. We should probably do 'uname -r | cut -d. -f1' to get the kernel major-version and then -lt for numeric comparison.

**Comment by dagsagrinbergs** [comment]
Solved on my end- realised you CAN do a manual source install on 10.12, so I got it working that way :).

**Comment by dak180** [comment]
@dagsagrinbergs you mentioned zsh; does it work in bash?

**Comment by dagsagrinbergs** [comment]
`sudo: ./Fink.sh: command not found` ...bash doesn't even want to try and execute it

**Comment by dak180** [comment]
@dagsagrinbergs and just to confirm: you are using the copy downloaded from the [release page](https://github.com/fink/scripts/releases/latest)?

**Comment by dagsagrinbergs** [comment]
I was using this one: https://github.com/fink/scripts/blob/master/srcinstaller/Install%20Fink.tool
