### ISSUE TITLE
Does not install on Mac OS X 10.13.6 Sierra

### ISSUE THREAD

**Issue by pipedream** [fink/scripts#46]
We get this issue on 10.13.6
https://sourceforge.net/p/fink/mailman/message/36298093/
https://stackoverflow.com/questions/51661606/fixing-fink-after-updating-to-high-sierra

Using Install Fink.tool. This is not a fink update, it is a first install.

**Comment by dak180** [comment]
@pipedream What exactly are you seeing when you run the `Install Fink.tool`?

**Comment by dak180** [comment]
Closing this until there is more info.
