### ISSUE TITLE
JKD being deprecated

### ISSUE THREAD

**Issue by jsruth1** [fink/scripts#49]
Hello. Trying to use Graphic Converter with SVG image files. It pointed me to install Fink. Tried to, but Terminal script tells me that I need the JDK. Java in turn says that is being deprecated. I am not a developer; hope it's OK to submit this here. Thanks.

**Comment by nieder** [comment]
Can you post the URL or announcement where it says the JDK is being deprecated? The main JDK download site I see doesn't mention anything: https://www.oracle.com/technetwork/java/javase/downloads/index.html Thanks.

The JDK8u201 download from there definitely works.

**Comment by jsruth1** [comment]
Hi, here is what I saw:
https://www.java.com/en/download/faq/jdk9_plugin.xml

Jeff

On Mar 24, 2019, at 12:42 PM, nieder <notifications@github.com<mailto:notifications@github.com>> wrote:


Can you post the URL or announcement where it says the JDK is being deprecated? The main JDK download site I see doesn't mention anything: https://www.oracle.com/technetwork/java/javase/downloads/index.html Thanks.

The JDK8u201 download from there definitely works.

**Comment by nieder** [comment]
That says that the _browser plugin_ is being deprecated for Java9. The Java9 JDK is definitely still good. Even Java8 JDK is available, although I think it's going to stop receiving updates very soon.

**Comment by akhansen** [comment]
Just as followup so that I can complain about Java on macOS once more, the situation is confused compared to other platforms:

- The JRE is just the browser plugin and insta

- 

-

**Comment by jsruth1** [comment]
Ok. Script in Terminal stopped, saying I need it. Do you know how I get it?

Thanks.

Jeff

On Mar 27, 2019, at 01:32, nieder <notifications@github.com<mailto:notifications@github.com>> wrote:


That says that the browser plugin is being deprecated for Java9. The Java9 JDK is definitely still good. Even Java8 JDK is available, although I think it's going to stop receiving updates very soon.

**Comment by jsruth1** [comment]
Neider responded, thanks. Not sure where to get the JDK…

Jeff

On Mar 27, 2019, at 1:35 AM, Alexander Hansen <notifications@github.com<mailto:notifications@github.com>> wrote:


Just as followup so that I can complain about Java on macOS once more, the situation is confused compared to other platforms:

  *   The JRE is just the browser plugin and insta

  *
  *

**Comment by nieder** [comment]
https://www.oracle.com/technetwork/java/javase/downloads/index.html
Get either version 11 or version 8 of the JDK.

**Comment by jsruth1** [comment]
Thanks.

On Mar 28, 2019, at 1:35 AM, nieder <notifications@github.com<mailto:notifications@github.com>> wrote:


https://www.oracle.com/technetwork/java/javase/downloads/index.html
Get either version 11 or version 8 of the JDK.
