### ISSUE TITLE
Fink Installation Failed

### ISSUE THREAD

**Issue by sabaferdous12** [fink/scripts#50]
I am trying to install fink but it fails with this error message. It looks like the server (http://distfiles.master.finkmirrors.net/distfiles/) to download the tarballs is not available...

Can you please fix this?

BOOTSTRAP PHASE ONE: download tarballs.

curl --connect-timeout 30 -f -L -A 'fink/0.44.1' -O http://distfiles.master.finkmirrors.net/distfiles/dpkg_1.10.21.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: distfiles.master.finkmirrors.net
### execution of curl failed, exit code 6
Downloading the file "dpkg_1.10.21.tar.gz" failed

**Comment by akhansen** [comment]
There was an issue with the finkmirrors.net domain, but that's fixed now.  Also, there is now an alternative download location for the essential package files.  Sorry for not seeing this earlier.
