### ISSUE TITLE
Error saying Perl (5.0108004) is current not supported by Fink

### ISSUE THREAD

**Issue by coep05** [fink/scripts#51]
I got error while installing Fink on MacOS Mojave 10.14.5.

Mirror for The Apache Project? [1] 

Writing updated configuration to '/sw/etc/fink.conf'...
plist is dpkg-bootstrap
Sorry, this version of Perl (5.018004) is currently not supported by Fink.

**Comment by nieder** [comment]
Yes. Unfortunately, Apple bumped the system-perl version in the 10.14.5 update (something they'd never done before in point updates), breaking building new perlmods and even fresh installing.

Tracking it here: https://github.com/fink/fink/issues/187

**Comment by nieder** [comment]
Fixed when we released 0.45.0 and the 10.14.5 dist back in August 2019.
