### ISSUE TITLE
Installations fails: MacBook Air: Mac 10.15.5

### ISSUE THREAD

**Issue by ouboub** [fink/scripts#54]
Hi 
I started my new MacBook (2019) yesterday, I downloaded the Installer, it downloads and installs Xcode but then
then the following message pops up and I quote 
to use the 'java' command line tool you need to install a JDK
click more info
but when I do that I am informed that the adobe flash paler end of life bla bla but no download.
I am stuck, what shall I do?
regards

Uwe Brauer

**Comment by dak180** [comment]
@ouboub please post the url that it sends you to; we rely on the system to send you somewhere sensible that you should be able to get to the [right page](https://www.oracle.com/java/technologies/javase-jdk11-downloads.html) within a few clicks because oracle is constantly revamping their site.

**Comment by ouboub** [comment]
> @ouboub please post the url that it sends you to; we rely on the system to send you somewhere sensible that you should be able to get to the [right page](https://www.oracle.com/java/technologies/javase-jdk11-downloads.html) within a few clicks because oracle is constantly revamping their site.

that is the page https://www.adobe.com/products/flashplayer/end-of-life.html

so shall I simply visit the link you send me or wait till you upgrade the script?

**Comment by dak180** [comment]
@ouboub likely the web page it initially sends you to is redirecting to the flash end of life page (not sure why given two different companies and products); is there any chance of getting that initial url?

**Comment by dak180** [comment]
@ouboub since it seems unlikely that this will be fixed in the os try this [updated script](https://github.com/dak180/scripts/raw/topic/setup/srcinstaller/Install%20Fink.tool) and let me know if that works for you.

**Comment by ouboub** [comment]
this is what happens:
Checking for Java...
Unable to find any JVMs matching version "1.6+".
JDK is not installed, fetching...
Fetching https://download.java.net/java/GA/15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_osx-x64_bin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: Unable to fetch https://download.java.net/java/GA/15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_osx-x64_bin.tar.gz

**Comment by dak180** [comment]
@ouboub try the [fixed url](https://github.com/dak180/scripts/raw/topic/setup/srcinstaller/Install%20Fink.tool).

**Comment by ouboub** [comment]
Checking for Java...
Unable to find any JVMs matching version "1.6+".
JDK is not installed, fetching...
Fetching https://download.java.net/java/GA/15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_osx-x64_bin.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
error: Unable to fetch https://download.java.net/java/GA/15.0.2/0d1cfde4252546c6931946de8db48ee2/7/GPL/openjdk-15.0.2_osx-x64_bin.tar.gz

**Comment by ouboub** [comment]
that is odd, I will check again, seems the same error

**Comment by ouboub** [comment]
> @ouboub try the [fixed url](https://github.com/dak180/scripts/raw/topic/setup/srcinstaller/Install%20Fink.tool).

I am confused, both: this link and the changed script you posted, are identical, (using meld in Ubuntu) so
there is no surprise that I obtain the same error.
what do I miss

**Comment by dak180** [comment]
@ouboub try clearing your browser's cache.

**Comment by ouboub** [comment]
> @ouboub try clearing your browser's cache.

I did, I used a different browser even, but wether I download
@ouboub try the fixed url.

or
@ouboub since it seems unlikely that this will be fixed in the os try this updated script and let me know if that works for you.

it does not matter, I always obtain the **same** scripts

**Comment by dak180** [comment]
@ouboub well, not sure why github is not doing the right thing for you (it works here) but try this [finely crafted link](https://raw.githubusercontent.com/dak180/scripts/f12528e90052924abe7a13f02c92c4de5d8e7528/srcinstaller/Install%20Fink.tool).

**Comment by ouboub** [comment]
I am deeply sorry but this is the same file.
Shall we proceed by email?

**Comment by ouboub** [comment]
> @ouboub well, not sure why github is not doing the right thing for you (it works here) but try this [finely crafted link](https://raw.githubusercontent.com/dak180/scripts/f12528e90052924abe7a13f02c92c4de5d8e7528/srcinstaller/Install%20Fink.tool).

Since it does not work. Can’t you make a branch and push ?
So that I can pull the corrected script once and for all

**Comment by dak180** [comment]
@ouboub it already is in a [branch](https://github.com/dak180/scripts/blob/topic/setup/srcinstaller/Install%20Fink.tool), dak180/scripts@f12528e90 being the relevant change.

**Comment by ouboub** [comment]
I cloned it with git (and also with hg and the hg-git plugin)
I don't see this commit

git log --all

so the latest commits are from 2020 (I am a mercurial user, with basic git knowledge)

* commit dd8059d274de4acd243a02ce77291cd02bf546e4 (HEAD -> master, tag: setup/0.45.2, origin/master, origin/HEAD)
| Author: Hanspeter Niederstrasser <nieder@users.sourceforge.net>
| Date:   Fri Oct 2 21:12:57 2020 -0500
|
|     Update for fink-0.45.2
|
* commit 71c1a2f4e9648ed292e9dd0c4028d49a50aab42e
| Author: Hanspeter Niederstrasser <nieder@users.sourceforge.net>
| Date:   Sat Mar 28 06:33:00 2020 -0500
|
|     Add instructions for making a new release of this script.
|
* commit ef3d3aa1c26b6fa909b37d75c1843693ff5bff59 (tag: setup/0.45.1)
| Author: Hanspeter Niederstrasser <nieder@users.sourceforge.net>
| Date:   Sat Mar 28 06:18:16 2020 -0500
|
|     Update for fink-0.45.1

**Comment by ouboub** [comment]
>>> "d" == dak180  <notifications@github.com> writes:

> @ouboub it already is in a
> [branch](https://github.com/dak180/scripts/blob/topic/setup/srcinstaller/Install%20Fink.tool),
> dak180/scripts@f12528e90 being the relevant change.


Ok, now I understand this is a different repository 

I was looking in 

https://github.com/fink/scripts.git

But it in

https://github.com/dak180/scripts.git

Github, sigh

**Comment by ouboub** [comment]
> @ouboub it already is in a [branch](https://github.com/dak180/scripts/blob/topic/setup/srcinstaller/Install%20Fink.tool), [dak180/scripts@f12528e](https://github.com/dak180/scripts/commit/f12528e90) being the relevant change.

RESOLVED: when cloning that repository, and using its corresponding script, I can confirm that it now works, thanks a lot.
I will close the issue now
