### ISSUE TITLE
Script finally returns an error, that I attach

### ISSUE THREAD

**Issue by ouboub** [fink/scripts#55]
Hi

so after the link was fixed (thanks), I obtained the following error, after some 20 min of compiling:
 dists/stable/main/binary-darwin-x86_64
New package: dists/stable/main/binary-darwin-x86_64/base/libiconv-dev_1.15-2_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/debianutils_4.4-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/apt-dev_0.5.4-1061_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/libgettext8-dev_0.19.8.1-2_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/unzip_6.0-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/apt-shlibs_0.5.4-1061_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/libgettext8-shlibs_0.19.8.1-2_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/bzip2_1.0.6-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/gzip_1.9-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/dpkg_1.10.21-1248_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/fink_0.45.2-151_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/apt_0.5.4-1061_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/fink-mirrors_0.43.0.1-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/gettext-bin_0.19.8.1-2_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/bzip2-dev_1.0.6-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/libncurses5-shlibs_5.9-20110507-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/sensible-utils_0.0.7-4_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/bzip2-shlibs_1.0.6-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/tar_1.29-2_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/dpkg-base-files_0.4-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/ncurses_5.9-20110507-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/libiconv-bin_1.15-2_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/gettext-doc_0.19.8.1-2_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/libiconv_1.15-2_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/libncurses5_5.9-20110507-1_darwin-x86_64.deb
New package: dists/stable/main/binary-darwin-x86_64/base/base-files_1.9.17-1_darwin-x86_64.deb
Downloading the indexes of available packages in the binary distribution.
/opt/sw/bin/apt-get-lockwait -q update
Err http://bindist.finkmirrors.net stable/main Packages
  404 Not Found
Ign http://bindist.finkmirrors.net stable/main Release
Failed to fetch http://bindist.finkmirrors.net/10.15/dists/stable/main/binary-darwin-x86_64/Packages  404 Not Found
Reading Package Lists...
Building Dependency Tree...
E: Some index files failed to download, they have been ignored, or old ones used instead.
### execution of /opt/sw/bin/apt-get-lockwait failed, exit code 100
WARNING: Failure while updating indexes.

ERROR: Bootstrap phase 2 failed!

not sure who is now the culprit

**Comment by TheSin-** [comment]
There is not binary distribution, set it to no in /opt/sw/etc/fink.conf or say no during the bootstrap question

**Comment by ouboub** [comment]
ok, installation seems to work, another problem occurred. I will open a new issue, please tell me whether this is the correct place.
