### ISSUE TITLE
Install Fink.tool should conditional the default install path

### ISSUE THREAD

**Issue by nieder** [fink/scripts#57]
In commit cc3b502b, we changed the default install path from `/sw` to `/sw/opt` to match the change in Fink. For fink-0.45.3, we've changed the default back to `/sw` for macOS <= 10.14 (darwin18 and earlier). `Install Fink.tool` should also conditional its default install path on the OS version.

**Comment by dak180** [comment]
If anyone can check the output of `uname -r | cut -d. -f1` on macos 11 that would be good.

**Comment by nieder** [comment]
BigSur = 20.
