### ISSUE TITLE
Install Fink.tool fails when trying to find XQuartz

### ISSUE THREAD

**Issue by Michael0x18** [fink/scripts#59]
OS: MacOS 10.15.6 (Catalina)
Output:
`Checking for XQuartz...
No receipt for 'org.macosforge.xquartz.pkg' found at '/'.
XQuartz is not installed, fetching...
Fetching https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0    10    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 403
error: Unable to fetch https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg`

**Comment by dak180** [comment]
@Michael0x18 please try the [latest version](https://github.com/fink/scripts/raw/master/srcinstaller/Install%20Fink.tool) of the script.

**Comment by dak180** [comment]
Closing as likely fixed.
